osx_image: xcode7.3
language: objective-c
script:
  - set -o pipefail && xcodebuild build -project NibDesignableDemo/NibDesignableDemo.xcodeproj -scheme NibDesignableDemo -sdk iphonesimulator | xcpretty -f `xcpretty-travis-formatter`
  - set -o pipefail && xcodebuild test -project NibDesignableDemo/NibDesignableDemo.xcodeproj -scheme NibDesignableDemo -sdk iphonesimulator | xcpretty -f `xcpretty-travis-formatter`
  - swiftlint lint --strict
before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
  - gem install xcpretty xcpretty-travis-formatter
